-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id smallserial NOT NULL,
    username character varying COLLATE pg_catalog."default",
    password character varying COLLATE pg_catalog."default",
    CONSTRAINT admin_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employer
(
    employer_id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    surname character varying COLLATE pg_catalog."default" NOT NULL,
    business character varying COLLATE pg_catalog."default",
    phonenumber character varying COLLATE pg_catalog."default",
    date date,
    CONSTRAINT employer_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS public.invoice
(
    id serial NOT NULL,
    job_id integer,
    amount numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    date time with time zone,
    CONSTRAINT invoice_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.job
(
    id serial NOT NULL,
    employer_id integer,
    price_id integer,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    date time with time zone,
    CONSTRAINT job_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment
(
    id serial NOT NULL,
    worker_id integer,
    job_id integer,
    paytype_id integer,
    amount numeric(10, 2) NOT NULL,
    payment_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    date time with time zone,
    CONSTRAINT payment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.paytype
(
    id serial NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    date time with time zone,
    CONSTRAINT paytype_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.price
(
    id serial NOT NULL,
    fulltime numeric(10, 2) NOT NULL,
    halftime numeric(10, 2) NOT NULL,
    overtime numeric(10, 2) NOT NULL,
    date timestamp with time zone,
    CONSTRAINT price_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.work
(
    id serial NOT NULL,
    job_id integer,
    worker_id integer,
    worktype_id integer,
    workgroup_id integer,
    description text COLLATE pg_catalog."default",
    work_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    date time with time zone,
    CONSTRAINT work_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.worker
(
    id serial NOT NULL,
    fname character varying COLLATE pg_catalog."default" NOT NULL,
    lname character varying COLLATE pg_catalog."default" NOT NULL,
    tel character varying COLLATE pg_catalog."default",
    iban character varying COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    date time with time zone,
    CONSTRAINT worker_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.workgroup
(
    id serial NOT NULL,
    job_id integer,
    worktype_id integer,
    workcount integer NOT NULL,
    description text COLLATE pg_catalog."default",
    date time with time zone,
    CONSTRAINT workgroup_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.worktype
(
    id serial NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    no character varying COLLATE pg_catalog."default" NOT NULL,
    date time with time zone,
    CONSTRAINT worktype_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT invoice_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job
    ADD CONSTRAINT job_employer_id_fkey FOREIGN KEY (employer_id)
    REFERENCES public.employer (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.job
    ADD CONSTRAINT job_price_id_fkey FOREIGN KEY (price_id)
    REFERENCES public.price (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment
    ADD CONSTRAINT payment_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment
    ADD CONSTRAINT payment_paytype_id_fkey FOREIGN KEY (paytype_id)
    REFERENCES public.paytype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payment
    ADD CONSTRAINT payment_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES public.worker (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT work_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT work_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES public.worker (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT work_workgroup_id_fkey FOREIGN KEY (workgroup_id)
    REFERENCES public.workgroup (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work
    ADD CONSTRAINT work_worktype_id_fkey FOREIGN KEY (worktype_id)
    REFERENCES public.worktype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.workgroup
    ADD CONSTRAINT workgroup_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.job (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.workgroup
    ADD CONSTRAINT workgroup_worktype_id_fkey FOREIGN KEY (worktype_id)
    REFERENCES public.worktype (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;